/* jsmerge.c: copyright Mike Arnautov 2015-2017, licensed
 * under GPL (version 3 or later) or the Modified BSD Licence,
 * whichever is asserted by the supplied LICENCE file.
 */   
#include <stdio.h>
#include <string.h>
int main (int argc, char **argv)
{
  char outfile[256];
  char gname[64];
  char line[8192];
  char *lptr;
  char *sptr;
  FILE *fin;
  FILE *fin2;
  FILE *fout;
  if (argc != 5)
  {
    printf("Usage: %s <template_file> <js_file> <output_dir> <game_name>\n", *argv);
    return(1);
  }
/*
 * Open the three files.
 */
  if ((fin = fopen(*(argv + 1), "r")) == NULL)
  {
    printf("Unable to open: %s\n", *(argv + 1));
    return(1);
  }
  if ((fin2 = fopen(*(argv + 2), "r")) == NULL)
  {
    printf("Unable to open: %s\n", *(argv + 2));
    fclose(fin);
    return(1);
  }
  strncpy(gname, *(argv + 4), 64);
  sprintf(outfile, "%s/%s.html", *(argv + 3), gname);
  if ((fout = fopen(outfile, "w")) == NULL)
  {
    printf("Unable to open: %s\n", outfile);
    fclose(fin);
    fclose(fin2);
    return(1);
  }
/*
 * Copy the template up to but not including a line containing %JAVASCRIPT%.
 */
  while (fgets(line, sizeof(line), fin))
  {
    if (strstr(line, "%JAVASCRIPT%")) break;
    fputs(line, fout);
  }
/*
 * Copy the next line, opening a script tag.
 */
  fgets(line, sizeof(line), fin);
  fputs(line, fout);
/*
 * Now copy the JS code generated by emscripten.
 */
  while (fgets(line, sizeof(line), fin2))
    fputs(line, fout);
  fclose(fin2);
/*
 * Copy the rest of the template, replacing %NAME% with gname.
 */
  while (fgets(line, sizeof(line), fin))
  {
    lptr = line;
    while ((sptr = strstr(lptr, "%NAME%")) != NULL)
    {
      *sptr = 0;
      fprintf(fout, "%s%s", lptr, gname);
      lptr = sptr + 6;
    }
    if (lptr)
      fputs(lptr, fout);
  }
/*
 * All done.
 */
  fclose(fin);
  return(0);
}
/*****************************************************************/
